/*export const LOAD_PRODUCTS_SUCCESS ='LOAD_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_SUCCESS ='ADD_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_SUCCESS ='DELETE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS ='UPDATE_PRODUCT_SUCCESS';
export const DELETEALL_PRODUCT_SUCCESS="DELETEALL_PRODUCT_SUCCESS";

export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const CHECK_ALL_SUCCESS="CHECK_ALL_SUCCESS";
export const CHECK_DESCRIPTION="CHECK_DESCRIPTION";
export const CHECK_PRICE="CHECK_PRICE";
export const CHECK_QUANTITY="CHECK_QUANTITY";
export const CHECK_MANUFACTURER="CHECK_MANUFACTURER";
 */
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const ADMIT_SHOWJOINEE_MODAL="ADMIT_SHOWJOINEE_MODAL";

export const CHECK_PHONE_NUMBER_SUCCESS = 'CHECK_PHONE_NUMBER_SUCCESS';
