
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const ADMIT_SHOWJOINEE_MODAL="ADMIT_SHOWJOINEE_MODAL";

export const CHECK_PHONE_NUMBER_SUCCESS = 'CHECK_PHONE_NUMBER_SUCCESS';
export const LOAD_LOGGEDIN_USER_DATA_SUCCESS = 'LOAD_LOGGEDIN_USER_DATA_SUCCESS';
export const UPDATE_USER_CHAT_SUCCESS = 'UPDATE_USER_CHAT_SUCCESS';
export const UPDATE_OPPOSITE_USER_CHAT_SUCCESS = 'UPDATE_OPPOSITE_USER_CHAT_SUCCESS';
export const UPDATE_OPPOSITE_USER_CHAT_TRIGGER_SUCCESS = 'UPDATE_OPPOSITE_USER_CHAT_TRIGGER_SUCCESS';
